# Database configuration (can be overridden by environment variables: DB_URL, DB_USERNAME, DB_PASSWORD)
# For Docker: use host.docker.internal
#db.url=jdbc:postgresql://host.docker.internal:5432/labs_oop
# For local development: use localhost
db.url=jdbc:postgresql://localhost:5432/labs_oop
db.username=postgres
db.password=12345678